# defaults file for install

conda_folder: "~/.conda"
conda_installer_url: https://github.com/conda-forge/miniforge/releases/download/22.11.1-4/Mambaforge-22.11.1-4-Linux-x86_64.sh
conda_installer_checksum: sha256:16c7d256de783ceeb39970e675efa4a8eb830dcbb83187f1197abfea0bf07d30
conda_executable: mamba
conda_download_timeout: 300
conda_activate_alias: ""
